import type { Profile } from "./types";

// SK's personal profile. This is the prototype configuration; when Evidence
// is generalized for coaching clients and Ignite Healing AI, profiles like
// this one will be created per user (names like Anthony and Sunny below are
// SK-specific and intentionally live here, not in the UI code).

export const defaultProfile: Profile = {
  appName: "Evidence",
  tagline:
    "When I feel the urge for intensity, help me find the need underneath it and show me evidence that I'm changing.",

  corePromise: [
    "You do not have to decide right now.",
    "Pause.",
    "Notice.",
    "Choose one next step.",
    "Collect evidence.",
  ],

  feelings: [
    { id: "restless", label: "restless" },
    { id: "bored", label: "bored" },
    { id: "lonely", label: "lonely" },
    { id: "overwhelmed", label: "overwhelmed" },
    { id: "angry", label: "angry" },
    { id: "aroused", label: "horny / aroused" },
    { id: "sad", label: "sad" },
    { id: "grief", label: "grief" },
    { id: "stuck", label: "stuck" },
    { id: "excited", label: "excited" },
    { id: "activated", label: "activated" },
    { id: "numb", label: "numb" },
    { id: "ashamed", label: "ashamed" },
    { id: "anxious", label: "anxious" },
    { id: "rejected", label: "rejected" },
    { id: "disappointed", label: "disappointed" },
    { id: "craving-relief", label: "craving relief" },
    { id: "craving-stimulation", label: "craving stimulation" },
    { id: "craving-transformation", label: "craving transformation" },
    { id: "craving-proof", label: "craving proof I'm changing" },
    { id: "dont-know", label: "don't know" },
  ],

  dysregulatorGroups: [
    {
      id: "physical",
      label: "Physical",
      options: [
        { id: "hungry", label: "hungry" },
        { id: "thirsty", label: "thirsty" },
        { id: "tired", label: "tired" },
        { id: "sick", label: "sick" },
        { id: "headache", label: "headache" },
        { id: "pain", label: "pain" },
        { id: "overstimulated", label: "overstimulated" },
        { id: "understimulated", label: "understimulated" },
        { id: "no-movement", label: "haven't moved my body" },
        { id: "forgot-medication", label: "forgot medication" },
        { id: "medication-wearing-off", label: "medication wearing off" },
        { id: "hormonal-changes", label: "hormonal changes" },
      ],
    },
    {
      id: "emotional",
      label: "Emotional",
      options: [
        { id: "lonely", label: "lonely" },
        { id: "rejected", label: "rejected" },
        { id: "ashamed", label: "ashamed" },
        { id: "disappointed", label: "disappointed" },
        { id: "grieving", label: "grieving" },
        { id: "overwhelmed", label: "overwhelmed" },
        { id: "angry", label: "angry" },
        { id: "anxious", label: "anxious" },
        { id: "scared", label: "scared" },
      ],
    },
    {
      id: "life-stressors",
      label: "Life Stressors",
      options: [
        { id: "kid-stress", label: "kid stress" },
        { id: "co-parent-stress", label: "co-parent stress" },
        { id: "ex-stress", label: "ex stress" },
        { id: "work-stress", label: "work stress" },
        { id: "bills", label: "bills" },
        { id: "money-stress", label: "money stress" },
        { id: "legal-stress", label: "legal stress" },
        { id: "relationship-stress", label: "relationship stress" },
        { id: "family-conflict", label: "family conflict" },
        { id: "uncertainty", label: "uncertainty" },
        { id: "decision-fatigue", label: "decision fatigue" },
        { id: "too-many-responsibilities", label: "too many responsibilities" },
      ],
    },
    {
      id: "recovery-risks",
      label: "Recovery Risks",
      options: [
        { id: "isolation", label: "isolation" },
        { id: "secrecy", label: "secrecy" },
        { id: "avoiding-support", label: "avoiding support" },
        { id: "avoiding-feelings", label: "avoiding feelings" },
        { id: "avoiding-a-decision", label: "avoiding a decision" },
        { id: "craving-intensity", label: "craving intensity" },
        { id: "craving-escape", label: "craving escape" },
        { id: "craving-relief", label: "craving relief" },
      ],
    },
    {
      id: "other",
      label: "Other",
      options: [{ id: "dont-know", label: "I don't know" }],
    },
  ],

  bodySensations: [
    { id: "buzzing", label: "buzzing" },
    { id: "eye-twitching", label: "eye twitching" },
    { id: "tight-chest", label: "tight chest" },
    { id: "racing-thoughts", label: "racing thoughts" },
    { id: "cant-sit-still", label: "can't sit still" },
    { id: "exhausted", label: "exhausted" },
    { id: "body-pressure", label: "pressure in body" },
    { id: "stomach-knot", label: "knot in stomach" },
    { id: "heavy-body", label: "heavy body" },
    { id: "want-escape", label: "wanting to escape" },
    { id: "want-act-now", label: "wanting to act now" },
    { id: "urge-fix", label: "urge to fix something" },
    { id: "urge-big-decision", label: "urge to make a big decision" },
    { id: "urge-use", label: "urge to use" },
    { id: "dont-know", label: "don't know" },
  ],

  urges: [
    { id: "get-high", label: "get high" },
    { id: "spend-money", label: "spend money" },
    { id: "sexual-intensity", label: "seek sexual intensity" },
    { id: "text-someone", label: "text someone" },
    { id: "big-decision", label: "make a big decision" },
    { id: "create-chaos", label: "create chaos" },
    { id: "write-all-night", label: "write all night" },
    { id: "avoid-responsibility", label: "avoid responsibility" },
    { id: "disappear", label: "disappear" },
    { id: "quit-something", label: "quit something" },
    { id: "start-something", label: "start something" },
    { id: "dont-know", label: "don't know" },
  ],

  pauseMessage: [
    "You do not need to understand this yet.",
    "You only need to pause.",
    "Try one thing for 10 minutes.",
  ],

  interventionCategories: [
    {
      id: "stimulation",
      name: "Stimulation",
      useWhen: ["bored", "restless", "numb", "understimulated", "ADHD activation"],
      matchTags: [
        "bored",
        "restless",
        "numb",
        "understimulated",
        "buzzing",
        "cant-sit-still",
        "craving-stimulation",
        "craving-intensity",
        "no-movement",
        "create-chaos",
        "spend-money",
      ],
      interventions: [
        { id: "dance-one-song", label: "dance to one song" },
        { id: "loud-music", label: "loud music" },
        { id: "drum", label: "drum" },
        { id: "play-bass", label: "play bass" },
        { id: "cold-water-face", label: "cold water on face" },
        { id: "hold-ice", label: "hold ice" },
        { id: "sour-candy", label: "sour candy" },
        { id: "spicy-food", label: "spicy food" },
        { id: "lollipop", label: "suck on a lollipop" },
        { id: "sparkling-water", label: "drink sparkling water" },
        { id: "straw", label: "drink through a straw" },
        { id: "chew-gum", label: "chew gum" },
        { id: "race-timer", label: "race a 10-minute timer" },
        { id: "walk-sunny", label: "walk Sunny" },
      ],
    },
    {
      id: "relief",
      name: "Relief",
      useWhen: ["overwhelmed", "anxious", "exhausted", "can't do this"],
      matchTags: [
        "overwhelmed",
        "anxious",
        "exhausted",
        "tired",
        "sick",
        "headache",
        "pain",
        "overstimulated",
        "craving-relief",
        "craving-escape",
        "tight-chest",
        "heavy-body",
        "too-many-responsibilities",
        "want-escape",
        "disappear",
        "avoid-responsibility",
      ],
      interventions: [
        { id: "lie-down", label: "lie down" },
        { id: "weighted-blanket", label: "weighted blanket" },
        { id: "hot-shower", label: "hot shower" },
        { id: "prayer", label: "prayer" },
        { id: "breathing", label: "breathing" },
        { id: "pet-sunny", label: "pet Sunny" },
        { id: "nap", label: "nap" },
        { id: "reduce-stimulation", label: "reduce stimulation" },
        { id: "sit-outside", label: "sit outside" },
      ],
    },
    {
      id: "permission",
      name: "Permission",
      useWhen: ["a feeling wants to be felt", "shame", "grief", "pressure to act"],
      matchTags: [
        "ashamed",
        "sad",
        "grief",
        "grieving",
        "avoiding-feelings",
        "want-act-now",
        "dont-know",
      ],
      prompt:
        "I give myself permission to feel ______ without acting on it yet.",
      interventions: [
        { id: "write-sentence", label: "write the sentence" },
        { id: "voice-memo", label: "voice memo" },
        { id: "hand-on-chest", label: "hand on chest" },
        { id: "hand-on-belly", label: "hand on belly" },
        { id: "repeat-permission", label: "repeat: Permission is not action." },
      ],
      reminder: "Permission is not action.",
    },
    {
      id: "anger",
      name: "Anger",
      useWhen: ["resentful", "irritated", "activated", "defensive"],
      matchTags: [
        "angry",
        "activated",
        "body-pressure",
        "family-conflict",
        "co-parent-stress",
        "ex-stress",
      ],
      interventions: [
        { id: "unsent-rant", label: "unsent rant" },
        { id: "fast-walk", label: "fast walk" },
        { id: "stomp", label: "stomp" },
        { id: "pillow-hit", label: "pillow hit" },
      ],
      ask: ["What boundary do I want?"],
    },
    {
      id: "arousal",
      name: "Arousal",
      useWhen: ["erotic energy", "fantasy", "body buzz"],
      matchTags: ["aroused", "sexual-intensity"],
      interventions: [
        { id: "notice-sensation", label: "notice sensation" },
        { id: "breathe-into-sensation", label: "breathe into sensation" },
        { id: "delay-10", label: "delay action 10 minutes" },
      ],
      ask: [
        "Do I want pleasure?",
        "Do I want connection?",
        "Do I want power?",
        "Do I want release?",
        "Do I want escape?",
      ],
      reminder: "Arousal is allowed.",
    },
    {
      id: "creativity",
      name: "Creativity",
      useWhen: ["urge to get high and write", "idea spirals", "breakthrough hunger"],
      matchTags: [
        "write-all-night",
        "excited",
        "get-high",
        "start-something",
        "racing-thoughts",
      ],
      interventions: [
        { id: "sober-sprint", label: "15-minute sober writing sprint" },
        { id: "title-chapter", label: "title the chapter" },
        { id: "one-paragraph", label: "write one paragraph" },
        { id: "bad-writing", label: "bad writing allowed" },
      ],
    },
    {
      id: "connection",
      name: "Connection",
      useWhen: ["lonely", "people just left", "attachment ache"],
      matchTags: [
        "lonely",
        "rejected",
        "isolation",
        "avoiding-support",
        "secrecy",
        "text-someone",
        "scared",
      ],
      interventions: [
        { id: "text-friend", label: "text a friend" },
        { id: "thinking-of-you", label: "send a thinking-of-you message" },
        { id: "appreciation", label: "express appreciation" },
        { id: "call-someone", label: "call someone" },
        { id: "call-sponsor", label: "call sponsor" },
        { id: "pet-sunny-connection", label: "pet Sunny" },
      ],
      ask: ["Who do I wish was here?"],
    },
    {
      id: "gratitude",
      name: "Gratitude",
      useWhen: ["scarcity", "fear", "obsession", "spiraling"],
      matchTags: [
        "anxious",
        "racing-thoughts",
        "bills",
        "money-stress",
        "uncertainty",
        "scared",
      ],
      interventions: [
        { id: "grateful-10", label: "list 10 things I'm grateful for" },
        { id: "went-right-10", label: "list 10 things that went right today" },
        { id: "people-10", label: "list 10 people who care about me" },
        { id: "changed-10", label: "list 10 ways I've changed" },
      ],
    },
    {
      id: "memory",
      name: "Memory & Reality Check",
      useWhen: ["hopeless", "stuck", "nothing is changing"],
      matchTags: ["stuck", "disappointed", "numb", "craving-proof"],
      interventions: [
        { id: "photos-last-year", label: "look at photos from this day last year" },
        { id: "review-dashboard", label: "review evidence dashboard" },
        { id: "compare-six-months", label: "compare today to six months ago" },
        { id: "read-wins", label: "read previous wins" },
      ],
      ask: ["What would past me be surprised by today?"],
    },
    {
      id: "transformation",
      name: "Transformation / Evidence I'm Changing",
      useWhen: ["craving a big decision", "craving reinvention", "craving proof of growth"],
      matchTags: [
        "big-decision",
        "urge-big-decision",
        "craving-transformation",
        "craving-proof",
        "quit-something",
        "start-something",
        "avoiding-a-decision",
        "decision-fatigue",
        "urge-fix",
      ],
      interventions: [
        { id: "take-walk", label: "take a walk" },
        { id: "delay-20", label: "delay decision 20 minutes" },
        { id: "honest-sentence", label: "write one honest sentence" },
        { id: "text-sponsor", label: "text sponsor" },
        { id: "text-coach", label: "text coach" },
        { id: "not-yet-list", label: "create a \"not yet\" list" },
      ],
      ask: ["Am I craving change? Or evidence that I'm changing?"],
    },
  ],

  fallbackCategoryIds: ["relief", "stimulation", "connection"],

  reflectionOutcomes: [
    { id: "craving-passed", label: "craving passed" },
    { id: "craving-decreased", label: "craving decreased" },
    { id: "craving-stayed", label: "craving stayed" },
    { id: "acted-on-it", label: "I acted on it" },
    { id: "paused", label: "I paused" },
    { id: "reached-out", label: "I reached out" },
    { id: "learned-something", label: "I learned something" },
    { id: "still-dont-know", label: "I still don't know" },
  ],

  evidenceCategories: [
    { id: "pause", label: "Pauses" },
    { id: "support", label: "Support reach-outs" },
    { id: "craving-survived", label: "Cravings survived" },
    { id: "honest-moment", label: "Honest moments" },
    { id: "parenting-win", label: "Parenting wins" },
    { id: "recovery-win", label: "Recovery wins" },
    { id: "boundary-held", label: "Boundaries held" },
    { id: "difficult-conversation", label: "Difficult conversations" },
    { id: "meeting-attended", label: "Meetings attended" },
    { id: "repair", label: "Acts of repair" },
    { id: "sober-creative", label: "Sober creative sessions" },
    { id: "decision-delayed", label: "Decisions delayed" },
    { id: "other", label: "Other evidence" },
  ],

  evidenceExamples: [
    { text: "I paused.", category: "pause" },
    { text: "I waited 10 minutes.", category: "pause" },
    { text: "I told the truth.", category: "honest-moment" },
    { text: "I texted Anthony.", category: "support" },
    { text: "Asked for help.", category: "support" },
    { text: "I noticed the pattern.", category: "other" },
    { text: "I didn't make a decision while activated.", category: "decision-delayed" },
    { text: "Delayed a big decision.", category: "decision-delayed" },
    { text: "I let myself feel without acting.", category: "recovery-win" },
    { text: "I came back.", category: "recovery-win" },
    { text: "Boundary held.", category: "boundary-held" },
    { text: "Asked for what I needed.", category: "boundary-held" },
    { text: "Parenting win.", category: "parenting-win" },
    { text: "Recovery win.", category: "recovery-win" },
    { text: "Honest conversation.", category: "difficult-conversation" },
    { text: "Attended a meeting.", category: "meeting-attended" },
    { text: "Made amends.", category: "repair" },
    { text: "Chose repair over avoidance.", category: "repair" },
    { text: "Finished a hard task.", category: "other" },
    { text: "Took medication.", category: "recovery-win" },
    { text: "Exercised.", category: "recovery-win" },
    { text: "Ate a meal.", category: "recovery-win" },
    { text: "Chose rest.", category: "recovery-win" },
    { text: "Stayed present with discomfort.", category: "recovery-win" },
    { text: "Followed through on a commitment.", category: "other" },
    {
      text: "Did something sober that I thought I needed a substance to do.",
      category: "sober-creative",
    },
    {
      text: "Let someone influence me without losing myself.",
      category: "other",
    },
  ],

  supportContacts: [
    { id: "anthony", name: "Anthony", methods: ["text", "call"] },
    { id: "coach", name: "Coach", methods: ["text"] },
    { id: "trusted-friend", name: "Trusted Friend", methods: ["call"] },
  ],

  meetingListUrl: "https://www.aa.org/find-aa",

  prayer: [
    "Help me be honest.",
    "Help me pause.",
    "Help me choose the next right thing.",
  ],

  bigDecision: {
    intro: "You do not have to decide right now.",
    question: "Have I already decided?",
    branches: {
      yes: {
        title: "It sounds like the decision is made.",
        helper: "Let's process it before you act on it.",
        prompts: [
          "What does this decision move me toward?",
          "What does it help me avoid?",
          "Who will this affect, and have I talked to them?",
          "What would it cost me to act on this in 24 hours instead of right now?",
        ],
      },
      maybe: {
        title: "You're still exploring.",
        helper: "Let's get curious about what's underneath it.",
        prompts: [
          "What am I hoping this changes?",
          "What need is underneath this decision?",
          "What is the smallest version of this I could try first?",
          "Whose voice do I trust on this? What would they ask me?",
        ],
      },
      no: {
        title: "Nothing is decided yet.",
        helper: "Let's evaluate without pressure.",
        prompts: [
          "What are the real options, including \"not yet\"?",
          "What would future me, one year from now, thank me for?",
          "What evidence would help me decide?",
          "What happens if I wait a week?",
        ],
      },
    },
    specialPrompt:
      "Am I protecting my autonomy? Or protecting access to a behavior?",
  },
};
